[package]
name = "smpp_analyser"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
etherparse = "0.18.0"
lazy_static = "1.5.0"
libc = "0.2.172"
log = "0.4.27"
log4rs = "1.3.0"
once_cell = "1.21.3"
pcap = "2.2.0"
slog = "2.7.0"
slog-async = "2.8.0"
